version: '3'
services:
  openresty:
    image: openresty/openresty
    ports:
      - 8080:80
    volumes:
      - ./data:/mnt/ceph/download
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./lua_scripts:/usr/local/openresty/nginx/conf/lua_scripts
